# Local variables
[Local_variables]
newtolocal = ""
localdirectory = "" #Music

# Remote variables
[Remote_variables]
remotedirectory1 = "" #USB
remotedirectory2 = ""

[Discarded]
# Remote variables
;remote1 = ""
;remote2 = ""
